export const allTasks = [
  {
    type: "youtube",
    title: "Subscibe Youtube",
    desc: "Watch videos on our channel",
    reward: 500,
    link: "https://www.youtube.com/@KelpieNetwork",
    task_id: "1",
  },
  {
    type: "instagram",
    title: "Follow Instagram",
    desc: "Get to see product media from our team",
    reward: 500,
    link: "https://www.instagram.com/networkkelpie",
    task_id: "2",
  },
  {
    type: "telegram",
    title: "Join Channel",
    desc: "Get to know what kelpie is all about",
    reward: 500,
    link: "https://t.me/KelpieNetwork",
    task_id: "3",
  },
  {
    type: "twitter",
    title: "Follow Twitter",
    desc: "Don't miss out on community updates",
    reward: 500,
    link: "https://x.com/kelpienetwork",
    task_id: "4",
  },
  {
    type: "twitter",
    title: "Retweet Our Post",
    desc: "Twitter raids are exciting. Participate now!",
    reward: 500,
    link: "https://x.com/kelpienetwork",
    task_id: "5",
  },
  {
    type: "telegram",
    title: "Join Group",
    desc: "Connect with other Kelpians here. Join Now!",
    reward: 500,
    link: "https://t.me/kelpienetwork",
    task_id: "6",
  },
];
